version: "3.8"

services:
  app:
    image: anashk/laundrify-app:v1
    container_name: laundrify-app
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/var/www
      - ./storage:/var/www/storage
    ports:
      - "80:8000"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: laundrify-db-container
      DB_PORT: 3306
      DB_DATABASE: laundrify
      DB_USERNAME: root
      DB_PASSWORD: ""
    command: bash -c "php artisan serve --host=0.0.0.0 --port=8000"

  db:
    image: mysql:8.0
    container_name: laundrify-db-container
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laundrify
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/laundrify.sql:/docker-entrypoint-initdb.d/laundrify.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  db_data:
